library(broom.mixed)
library(kableExtra)
library(brms)
library(binom)
source("R/table_helper.R") 

# ----------- Table script usage -----------

# Paths
base_path <- "data"
out_path  <- "Table"
raw_path <- file.path(base_path, "df.csv")
S_path   <- file.path(base_path, "s.csv")
Si_path  <- file.path(base_path, "sirota.csv")

# Load data
df  <- load_clean_data(raw_path, type = "experiment")
s   <- load_clean_data(S_path,   type = "stengard")
si  <- load_clean_data(Si_path,  type = "sirota")

# Table 1: Definitions of simple heuristic rules.(Manually created in LaTeX)
# Table 2: Proportion of responses that exactly matched each model’s prediction, by format (Stengard)
table2 <- exact_match_table(s, out_path = file.path(out_path, "Table2.tex"),
                            caption = "Exact match rates across conditions.")
cat("\n=== Table 2: Heuristic/exact match summary ===\n")
print(table2)
# Table 3: Summary of candidate models included in the comparison.(Manually created in LaTeX)
# Table 4: Proportion of heuristic and Bayes predictions that fall on round values (%)
tbl_round <- bind_rows(
  round_prop_tbl(s  %>% filter(subject == "1_1"), "Standard"),
  round_prop_tbl(df %>% filter(subject == 1),     "Experiment")
)

results <- tbl_round %>% 
  mutate(across(-dataset, ~ percent(.x, accuracy = 0.1)))

make_round_table(results  ,
                 out_path = "Table/Table4.tex")

# Table 5: Proportion of responses that exactly matched each model’s prediction, by format (Experiment)
table5 <- exact_match_table(df, out_path = file.path(out_path, "Table5.tex"),
                            caption = "Exact match rates across conditions.")
cat("\n=== Table 5: Heuristic/exact match summary ===\n")
print(table5)

# Table A1: Bayes–Heuristic overlap (Task- and response-level, %)
s_flag  <- flag_overlaps(s) %>% 
  mutate(experiment = "Stengard",
         subject    = as.character(subject))   

df_flag <- flag_overlaps(df %>% dplyr::select(-rt)) %>% 
  mutate(experiment = "Exp",
         subject    = as.character(subject))  

all_flag <- bind_rows(s_flag, df_flag)

summary_tbl <- summarise_overlap(all_flag) %>% arrange(experiment, format)
latex_tbl_s <- make_main_overlap_table(s_flag)
latex_tbl_df <- make_main_overlap_table(df_flag)

# Table A2: Model-prediction overlap (%) for Stengard data
latex_overlap_table(s)
# Table A3: Model-prediction overlap (%) for experiment data
latex_overlap_table(df)

# Table E1: Posterior means of HAmix model parameters for each experiment and format.
# NOTE: This table is generated by the script '05_posterior.R'
#       because it requires the full posterior distribution output 
#       from the model.
